version: "3.7"
services:
  app:
    container_name: "zxctube_app"
    image: zxctube
    environment:
      HOST: "0.0.0.0"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - data:/data

volumes:
  data:

