version: "3.7"
services:
  db:
    container_name: "zxctube_db"
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zxctube
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  alembic_migrations:
    container_name: "zxctube_alembic"
    image: zxctube_alembic
    environment:
      ALEMBIC_DATABASE_URL: "postgresql://postgres:postgres@db/zxctube"
      DB_URL: "postgresql+asyncpg://postgres:postgres@db/zxctube"
    build:
      context: .
      dockerfile: alembic.dockerfile
    depends_on:
      - db

  app:
    container_name: "zxctube_app"
    image: zxctube
    environment:
      HOST: "0.0.0.0"
      DB_URL: "postgresql+asyncpg://postgres:postgres@db/zxctube"
      REDIS_URL: "redis://redis"
      LOCAL: false
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - data:/data
    depends_on:
      - alembic_migrations
#      - db
      - redis

  redis:
    container_name: "zxctube_redis"
    image: redis:7.2.0-alpine
    restart: always
    ports:
      - "6378:6379"

  celery:
    container_name: "zxctube_celery"
    image: zxctube_celery
    environment:
      REDIS_URL: "redis://redis"
    build:
      context: .
      dockerfile: celery.dockerfile
    volumes:
      - data:/data
    depends_on:
      - redis

  flower:
    container_name: "zxctube_flower"
    image: zxctube_flower
    environment:
      REDIS_URL: "redis://redis"
    build:
      context: .
      dockerfile: flower.dockerfile
    ports:
      - "5555:5555"
    depends_on:
      - celery

volumes:
  data:
  db-data:

