"""google_auth

Revision ID: d576b95123ad
Revises: e241ac1e56bc
Create Date: 2023-08-01 23:05:57.276654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd576b95123ad'
down_revision = 'e241ac1e56bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture', sa.String(), nullable=True))
    # op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'hashed_password')
    # op.drop_constraint(None, 'videos', type_='foreignkey')
    # op.create_foreign_key(None, 'videos', 'users', ['user'], ['id'], ondelete='restrict')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'videos', type_='foreignkey')
    # op.create_foreign_key(None, 'videos', 'users', ['user'], ['id'])
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=1024), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'picture')
    # ### end Alembic commands ###
