"""likes

Revision ID: e241ac1e56bc
Revises: 555df19f4478
Create Date: 2023-07-29 19:38:37.473820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e241ac1e56bc'
down_revision = '555df19f4478'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('videos', sa.Column('like_count', sa.Integer(), default=0, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'users', ['user'], ['id'])
    op.drop_column('videos', 'like_count')
    op.drop_table('videos_likes')
    # ### end Alembic commands ###
