"""followers

Revision ID: 555df19f4478
Revises: 5825ac0a7c26
Create Date: 2023-07-28 13:09:46.971584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555df19f4478'
down_revision = '5825ac0a7c26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('subscriber', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subscriber'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_constraint(None, 'videos', type_='foreignkey')
    # op.create_foreign_key(None, 'videos', 'users', ['user'], ['id'], ondelete='restrict')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'users', ['user'], ['id'])
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
